---

- hosts: linode.ianstewart.net

  become: true
  become_user: root


  tasks:
    - name: create deployment user
      user: 
        name: deployer 
        createhome: yes
        password: "{{ 'password' | password_hash('sha512') }}" 
        state: present 
        shell: /bin/bash
        groups: sudo

