---

- hosts: linode.ianstewart.net

  become: true
  become_user: root

  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.

  tasks:
    - name: create deployment user
      user: 
        name: deployer 
        createhome: yes
        password: {{password}} 
        state: present 
      register: newuser

    - name: Create folder
      file:
        path: "{{ item }}"
        state: directory
        owner: deployer
        group: deployer
        mode: 0775
      loop:
        - /home/deployer/.ssh

    - name: Copy Keys
      copy:
        src: keys/authorized_keys
        dest: /home/deployer/.ssh/authorized_keys   
        owner: ian
        group: ian
        mode: '0700'
